services:
  postgres:
    image: postgres:16-alpine
    container_name: desafio_aps_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: desafio
      POSTGRES_PASSWORD: desafio123
      POSTGRES_DB: desafio_aps
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
